PrintComment: Moving the EpicLoot modified config files into the EpicLoot plugins folder
CopyFile:
- From: config/EpicLoot/iteminfo.json
  To: plugins/RandyKnapp-EpicLoot/iteminfo.json
- From: config/EpicLoot/loottables.json
  To: plugins/RandyKnapp-EpicLoot/loottables.json
